In [9]:
import pickle, pandas, requests, tqdm, time

In [13]:
with open('gays.pickle', 'rb') as f:
    frame = pickle.load(f)

In [14]:
frame

       first_name           last_name         id  suicide     group
0            Катя            Адушкина  222267609        1  71194689
1       Анастасия          Третьякова    2615791        1  71194689
2         Nikolay         Nikolaevich       4041        1  71194689
3       Екатерина           Левинская  151576949        1  71194689
4           Антон             Соломка  140296111        1  71194689
5       Анастасия           Виленская  314042609        1  71194689
6       Анастасия            Соколова  118616259        1  71194689
7       Александр          Москаленко       2395        1  71194689
8       Анастасия             Волкова  161151316        1  71194689
9          Максим               Франк   94699094        1  71194689
10            Юра            Захарчук  242497826        1  71194689
11          Алина            Шабанова  162556812        1  71194689
12           Лили            Аксёнова   94260995        1  71194689
13         Оксана           Совушкина   88809814        1  71194689
14      Александр           Сергеевич       5665        1  71194689
15         Андрей             Соболев  101059709        1  71194689
16        Дмитрий             Седаков  300933852        1  71194689
17          Ирина            Звинцова  319096781        1  71194689
18      Александр             Борятин  398229629        1  71194689
19        Евгения            Грибкова   10013055        1  71194689
20       Вероника             Фрайман  120944917        1  71194689
21      Владислав           Янковский   18312547        1  71194689
22        Евгения           Булгакова       7188        1  71194689
23        Дмитрий           Прокофьев   98181088        1  71194689
24        Евгений             Окрушко   21539253        1  71194689
25           Катя            Адушкина  403171046        1  71194689
26          Алина              Котова  437868523        1  71194689
27        Дмитрий            Астафьев  101771464        1  71194689
28     Безымянный             Мальчик     235792        1  71194689
29      Екатерина          Перевалова    5098901        1  71194689
...           ...                 ...        ...      ...       ...
19821       Ксюша              Минчук   32701827        0  32486999
19822   Абылайхан            Ринатулы  197578799        0  32486999
19823       Алиса            Мизамбек  193682663        0  32486999
19824   Анастасия           Четыркина  186321888        0  32486999
19825       Элина         Кильдиярова  174987929        0  32486999
19826        Ваня           Станкевич  165350561        0  32486999
19827        Илья             Матыров  156109653        0  32486999
19828        Лина          Никольская  150582863        0  32486999
19829     Эльмира           Зиганшина  142137271        0  32486999
19830       Ксюша         Пономаренко  137290010        0  32486999
19831   Ростислав            Трофимов  137073314        0  32486999
19832      Богдан            Кривенко  119616255        0  32486999
19833     Евгения  Калинина-Беркутова  110022954        0  32486999
19834     Татьяна    Краснослободцева   85601476        0  32486999
19835         Яна            Шибляева   70122305        0  32486999
19836        Олег              Волков   62903056        0  32486999
19837        Юлия             Нуриева  279398711        0  32486999
19838       Наник             Суфиева  215824003        0  32486999
19839      Данила            Грошилин  195149028        0  32486999
19840   Анастасия            Киселёва  193141719        0  32486999
19841      Максим            Сверидов  182722161        0  32486999
19842      Никита             Крючков  153178013        0  32486999
19843        Олег              Фролов  141591004        0  32486999
19844       Алина           Алексеева  134703581        0  32486999
19845     Людмила            Аэробика  108901867        0  32486999
19846   Анастасия              Титова   93944667        0  32486999
19847      Андрей              Зайцев   83404524        0  32486999
19848     Марсель           Гайнуллин   62945225        0  32486999
19849       Роман            Захарків   61658324        0  32486999
19850        Юрец              Дедков  251475868        0  32486999

[19851 rows x 5 columns]

In [33]:
ids = list(frame['id'])

def chunks(lst, chunk_size):
    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]

ids = chunks(ids, 24)

In [34]:
api = 'https://api.vk.com/method/'
key = open("text.txt")
token = key.readline()[0:-1]

In [35]:
data = {
    'sex': [], 'relation': [],
    'political': [], 'religion': [], 'people_main': [], 'life_main': [],
    'smoking': [], 'alchol': [], 'groups': [],
}

In [47]:
for uid in tqdm.tqdm_notebook(ids):
    time.sleep(0.1)
    gays = requests.get(api + 'execute.infoUsers' + '?id=' + ','.join(list(map(str, uid)))+ '&v=5.85' + token).json()
    groups = gays['response'][1]
    get = gays['response'][0][0]
    if type(groups) == type(False):
        print(groups)
    for user in groups:
        tmp = []
        if type(user) == type(False):
            data['groups'].append([])
            continue
        for group in user['items']:
            tmp.append(group.setdefault('id', None))
        data['groups'].append(tmp)
        
    for x in get:
        data['sex'].append(x['sex'])
        data['religion'].append(x.setdefault('personal', {}).setdefault('religion', None))
        data['relation'].append(x.setdefault('relation', None))
        data['political'].append(x.setdefault('personal', {}).setdefault('political', None))
        data['people_main'].append(x.setdefault('personal', {}).setdefault('people_main', None))
        data['life_main'].append(x.setdefault('personal', {}).setdefault('life_main', None))
        data['smoking'].append(x.setdefault('personal', {}).setdefault('smoking', None))
        data['alchol'].append(x.setdefault('personal', {}).setdefault('alcohol', None))

HBox(children=(IntProgress(value=0, max=828), HTML(value='')))

In [48]:
import pickle
with open('FullFrame.pickle', 'wb') as f:
    pickle.dump(data, f)